#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branches=("main", "dev")
local_branch="$(git rev-parse --abbrev-ref HEAD)"

# Prevent push to protected branches.
if [[ ${protected_branches[*]} =~ $local_branch ]]
then echo "❌ PRE-PUSH HOOK: This branch is protected from a direct push..."
     false
fi

pnpm check:types || (
    echo '❌ PRE-PUSH HOOK: Failed...'
    false
)

# All checks passed. Push.
echo '✅ PRE-PUSH HOOK: Passed'